// <auto-generated />
using System;
using ChatSample.Modules.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatSample.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20250423090023_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatSample.Modules.Domains._0_Chats.Aggregate.Chat", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Owner1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Owner2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("creation")
                        .HasColumnType("datetime2");

                    b.HasKey("userId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ChatSample.Modules.Domains._0_Chats.Entity.Message", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BelongtouserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReply")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RepliedMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("creation")
                        .HasColumnType("datetime2");

                    b.HasKey("userId");

                    b.HasIndex("BelongtouserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ChatSample.Modules.Domains._0_Chats.Entity.Message", b =>
                {
                    b.HasOne("ChatSample.Modules.Domains._0_Chats.Aggregate.Chat", "Belongto")
                        .WithMany("Messages")
                        .HasForeignKey("BelongtouserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Belongto");
                });

            modelBuilder.Entity("ChatSample.Modules.Domains._0_Chats.Aggregate.Chat", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
